spring.application.name=eureka-server

# Eureka Server Config
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Basic Authentication - username: user, password: password
spring.security.user.name=user
spring.security.user.password=password
