spring.application.name=test-service
server.port=8082
spring.devtools.add-properties=false
# Where the Eureka Server is
eureka.client.service-url.defaultZone=http://user:password@localhost:8761/eureka
spring.devtools.restart.enabled=false
logging.level.web=DEBUG